name: gh-pages

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          # cache: 'pnpm'

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

      - name: Install and Build 🔧
        run: |
          pnpm i --no-frozen-lockfile
          pnpm build:demo

      - name: Deploy 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./packages/docs/dist # The folder the action should deploy.

          github_token: ${{ secrets.GITHUB_TOKEN }}
