name: gh-pages

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        node-version: [24.x]
    steps:
      - uses: actions/checkout@v5
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install and Test 🔧
        run: |
          pnpm i --no-frozen-lockfile
          pnpm --filter ./packages/sketch-ruler test

      - name: Build 🔧
        run: pnpm build:demo

      - name: Deploy 🚀
        uses: peaceiris/actions-gh-pages@v4
        with:
          publish_dir: ./packages/docs/dist # The folder the action should deploy.

          github_token: ${{ secrets.GITHUB_TOKEN }}
